apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: graphacademy-prod
bases:
- ../base

resources:
  - ingress.yaml
  - issuer.yaml
  - s3-proxy-ingress.yaml
  - s3-proxy-service.yaml
  - cronjob-certifications.yaml
  - cronjob-reminders.yaml

patches:
 - graphacademy-deployment.yaml
configMapGenerator:
  - name: ga-config-map
    envs:
      - .env
