apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/base
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: graphacademy
  name: graphacademy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: graphacademy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/base
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: graphacademy
    spec:
      containers:
        - image: 715633473519.dkr.ecr.us-east-1.amazonaws.com/graphacademy
          name: graphacademy
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
