name: Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v2.1.3

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        env:
          NEO4J_HOST: ${{ secrets.PROD_NEO4J_HOST }}
          NEO4J_USERNAME: ${{ secrets.PROD_NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.PROD_NEO4J_PASSWORD }}
        with:
          node-version: "16"

      - name: Install NPM Dependencies
        run: npm install

      # Sync content to production DB
      - name: Sync content to Prod Instance
        env:
          NEO4J_HOST: ${{ secrets.PROD_NEO4J_HOST }}
          NEO4J_USERNAME: ${{ secrets.PROD_NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.PROD_NEO4J_PASSWORD }}
        run: npm run sync:content

  sync-assets:
    runs-on: ubuntu-latest
    steps:
      # Sync images to CDN
      - name: Sync public/ to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.GA_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEVREL_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVREL_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.GA_AWS_REGION }}
          SOURCE_DIR: "public"
          DEST_DIR: "assets"

  restart-cluster:
    runs-on: ubuntu-latest
    needs:
      - update-database
    steps:
      # Restart cluster to download new content
      - name: Restart Cluster
        uses: kenju/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: "rollout restart -n graphacademy-prod deployment/graphacademy"

  invalidate-cache:
    runs-on: ubuntu-latest
    needs:
      - sync-assets
    steps:
      # Invalidate the CDN cache
      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.GA_CLOUDFRONT_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.GA_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEVREL_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVREL_SECRET_ACCESS_KEY }}
